/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.nrg.iu;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author nazaret
 */
public class PanelColor extends javax.swing.JPanel{

    /**
     * Creates new form PanelColor
     */
//    public PanelColor() {
//        initComponents();
//    }
    
    public PanelColor(Color c){
        initComponents();
       this.setSize(50, 50);
        this.boton.setBackground(c);
        this.boton.setSize(24,24);
    }
    
    public JButton getBoton(){
        return boton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(25, 35));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        boton.setPreferredSize(new java.awt.Dimension(30, 30));
        add(boton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    // End of variables declaration//GEN-END:variables
}
