/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionpractica2;

/**
 *
 * @author nazaret
 */
public class VentantaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentantaPrincipal
     */
    public VentantaPrincipal() {
        initComponents();
        
        this.setSize(600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones_herramientas = new javax.swing.ButtonGroup();
        botones_colores = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        boton_lapiz = new javax.swing.JButton();
        boton_linea = new javax.swing.JButton();
        boton_rectangulo = new javax.swing.JButton();
        boton_elipse = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        etiqueta_herramienta = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        boton_negro = new javax.swing.JButton();
        boton_rojo = new javax.swing.JButton();
        boton_azul = new javax.swing.JButton();
        boton_blanco = new javax.swing.JButton();
        boton_amarillo = new javax.swing.JButton();
        boton_verde = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        check_relleno = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        area_dibujo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Edición = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        boton_lapiz.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Lapiz.gif")); // NOI18N
        botones_herramientas.add(boton_lapiz);
        boton_lapiz.setFocusable(false);
        boton_lapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_lapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_lapiz);

        boton_linea.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Linea.gif")); // NOI18N
        botones_herramientas.add(boton_linea);
        boton_linea.setFocusable(false);
        boton_linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_linea);

        boton_rectangulo.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Rectangulo.gif")); // NOI18N
        botones_herramientas.add(boton_rectangulo);
        boton_rectangulo.setFocusable(false);
        boton_rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_rectangulo);

        boton_elipse.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Ovalo.gif")); // NOI18N
        botones_herramientas.add(boton_elipse);
        boton_elipse.setFocusable(false);
        boton_elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boton_elipse);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        etiqueta_herramienta.setText("Punto");
        jPanel3.add(etiqueta_herramienta, java.awt.BorderLayout.SOUTH);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(2, 3));

        boton_negro.setBackground(new java.awt.Color(1, 1, 1));
        botones_colores.add(boton_negro);
        boton_negro.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_negro.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_negro.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel5.add(boton_negro);

        boton_rojo.setBackground(new java.awt.Color(255, 0, 0));
        botones_colores.add(boton_rojo);
        boton_rojo.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_rojo.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_rojo.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel5.add(boton_rojo);

        boton_azul.setBackground(new java.awt.Color(0, 0, 255));
        botones_colores.add(boton_azul);
        boton_azul.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_azul.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_azul.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel5.add(boton_azul);

        boton_blanco.setBackground(new java.awt.Color(255, 255, 255));
        botones_colores.add(boton_blanco);
        boton_blanco.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_blanco.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_blanco.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel5.add(boton_blanco);

        boton_amarillo.setBackground(new java.awt.Color(255, 255, 0));
        botones_colores.add(boton_amarillo);
        boton_amarillo.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_amarillo.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_amarillo.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel5.add(boton_amarillo);

        boton_verde.setBackground(new java.awt.Color(0, 255, 0));
        botones_colores.add(boton_verde);
        boton_verde.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_verde.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_verde.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel5.add(boton_verde);

        jPanel6.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jPanel4, java.awt.BorderLayout.EAST);

        check_relleno.setText("Relleno ");
        jPanel6.add(check_relleno, java.awt.BorderLayout.EAST);
        jPanel6.add(jSeparator2, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(area_dibujo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        Archivo.setText("Archivo");
        jMenuBar1.add(Archivo);

        Edición.setText("Edición");
        jMenuBar1.add(Edición);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Edición;
    private javax.swing.JTextField area_dibujo;
    private javax.swing.JButton boton_amarillo;
    private javax.swing.JButton boton_azul;
    private javax.swing.JButton boton_blanco;
    private javax.swing.JButton boton_elipse;
    private javax.swing.JButton boton_lapiz;
    private javax.swing.JButton boton_linea;
    private javax.swing.JButton boton_negro;
    private javax.swing.JButton boton_rectangulo;
    private javax.swing.JButton boton_rojo;
    private javax.swing.JButton boton_verde;
    private javax.swing.ButtonGroup botones_colores;
    private javax.swing.ButtonGroup botones_herramientas;
    private javax.swing.JCheckBox check_relleno;
    private javax.swing.JLabel etiqueta_herramienta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
