/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionpractica4;

import java.awt.Color;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JToggleButton;

/**
 *
 * @author nazaret
 */
public class VentantaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentantaPrincipal
     */
    public VentantaPrincipal() {
        initComponents();
        
        this.setSize(600, 600);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones_herramientas = new javax.swing.ButtonGroup();
        botones_colores = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        boton_lapiz = new javax.swing.JToggleButton();
        boton_linea = new javax.swing.JToggleButton();
        boton_rectangulo = new javax.swing.JToggleButton();
        boton_elipse = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        etiqueta_herramienta = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        boton_negro = new javax.swing.JButton();
        boton_rojo = new javax.swing.JButton();
        boton_azul = new javax.swing.JButton();
        boton_blanco = new javax.swing.JButton();
        boton_amarillo = new javax.swing.JButton();
        boton_verde = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        check_relleno = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        lienzo = new aplicacionpractica4.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        menu_nuevo = new javax.swing.JMenuItem();
        menu_abrir = new javax.swing.JMenuItem();
        menu_guardar = new javax.swing.JMenuItem();
        Edición = new javax.swing.JMenu();
        menu_barra_estado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        botones_herramientas.add(boton_lapiz);
        boton_lapiz.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Lapiz.gif")); // NOI18N
        boton_lapiz.setFocusable(false);
        boton_lapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_lapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_lapiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_lapizMouseClicked(evt);
            }
        });
        jToolBar1.add(boton_lapiz);

        botones_herramientas.add(boton_linea);
        boton_linea.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Linea.gif")); // NOI18N
        boton_linea.setFocusable(false);
        boton_linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_linea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_lineaMouseClicked(evt);
            }
        });
        jToolBar1.add(boton_linea);

        botones_herramientas.add(boton_rectangulo);
        boton_rectangulo.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Rectangulo.gif")); // NOI18N
        boton_rectangulo.setFocusable(false);
        boton_rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_rectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_rectanguloMouseClicked(evt);
            }
        });
        jToolBar1.add(boton_rectangulo);

        botones_herramientas.add(boton_elipse);
        boton_elipse.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Ovalo.gif")); // NOI18N
        boton_elipse.setFocusable(false);
        boton_elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_elipse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_elipseMouseClicked(evt);
            }
        });
        jToolBar1.add(boton_elipse);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        etiqueta_herramienta.setText("Punto");
        jPanel3.add(etiqueta_herramienta, java.awt.BorderLayout.SOUTH);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(2, 3));

        boton_negro.setBackground(new java.awt.Color(1, 1, 1));
        botones_colores.add(boton_negro);
        boton_negro.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_negro.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_negro.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_negroMouseClicked(evt);
            }
        });
        jPanel5.add(boton_negro);

        boton_rojo.setBackground(new java.awt.Color(255, 0, 0));
        botones_colores.add(boton_rojo);
        boton_rojo.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_rojo.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_rojo.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_rojoMouseClicked(evt);
            }
        });
        jPanel5.add(boton_rojo);

        boton_azul.setBackground(new java.awt.Color(0, 0, 255));
        botones_colores.add(boton_azul);
        boton_azul.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_azul.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_azul.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_azulMouseClicked(evt);
            }
        });
        jPanel5.add(boton_azul);

        boton_blanco.setBackground(new java.awt.Color(255, 255, 255));
        botones_colores.add(boton_blanco);
        boton_blanco.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_blanco.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_blanco.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_blanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_blancoMouseClicked(evt);
            }
        });
        jPanel5.add(boton_blanco);

        boton_amarillo.setBackground(new java.awt.Color(255, 255, 0));
        botones_colores.add(boton_amarillo);
        boton_amarillo.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_amarillo.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_amarillo.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_amarilloMouseClicked(evt);
            }
        });
        jPanel5.add(boton_amarillo);

        boton_verde.setBackground(new java.awt.Color(0, 255, 0));
        botones_colores.add(boton_verde);
        boton_verde.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_verde.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_verde.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_verdeMouseClicked(evt);
            }
        });
        jPanel5.add(boton_verde);

        jPanel6.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jPanel4, java.awt.BorderLayout.EAST);

        check_relleno.setText("Relleno ");
        check_relleno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_rellenoMouseClicked(evt);
            }
        });
        jPanel6.add(check_relleno, java.awt.BorderLayout.EAST);
        jPanel6.add(jSeparator2, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        jPanel1.add(lienzo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        Archivo.setText("Archivo");

        menu_nuevo.setText("Nuevo");
        Archivo.add(menu_nuevo);

        menu_abrir.setText("Abrir");
        menu_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_abrirActionPerformed(evt);
            }
        });
        Archivo.add(menu_abrir);

        menu_guardar.setText("Guardar");
        menu_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guardarActionPerformed(evt);
            }
        });
        Archivo.add(menu_guardar);

        jMenuBar1.add(Archivo);

        Edición.setText("Edición");

        menu_barra_estado.setText("Ver barra de estado");
        Edición.add(menu_barra_estado);

        jMenuBar1.add(Edición);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_lapizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_lapizMouseClicked
        lienzo.setHerramienta(TipoHerramienta.PUNTOS);
        etiqueta_herramienta.setText("Punto");
    }//GEN-LAST:event_boton_lapizMouseClicked

    private void boton_lineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_lineaMouseClicked
        lienzo.setHerramienta(TipoHerramienta.LINEAS);
        etiqueta_herramienta.setText("Línea");
    }//GEN-LAST:event_boton_lineaMouseClicked

    private void boton_rectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_rectanguloMouseClicked
        lienzo.setHerramienta(TipoHerramienta.RECTANGULOS);
        etiqueta_herramienta.setText("Rectángulo");
    }//GEN-LAST:event_boton_rectanguloMouseClicked

    private void boton_elipseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_elipseMouseClicked
        lienzo.setHerramienta(TipoHerramienta.ELIPSES);
        etiqueta_herramienta.setText("Elipse");
    }//GEN-LAST:event_boton_elipseMouseClicked

    private void check_rellenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_rellenoMouseClicked
        if(check_relleno.isSelected())
            lienzo.setRelleno(true);
        else
            lienzo.setRelleno(false);
    }//GEN-LAST:event_check_rellenoMouseClicked

    private void boton_negroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_negroMouseClicked
        lienzo.setColor(Color.black);
    }//GEN-LAST:event_boton_negroMouseClicked

    private void boton_rojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_rojoMouseClicked
        lienzo.setColor(Color.red);
    }//GEN-LAST:event_boton_rojoMouseClicked

    private void boton_azulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_azulMouseClicked
        lienzo.setColor(Color.blue);
    }//GEN-LAST:event_boton_azulMouseClicked

    private void boton_blancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_blancoMouseClicked
        lienzo.setColor(Color.white);
    }//GEN-LAST:event_boton_blancoMouseClicked

    private void boton_amarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_amarilloMouseClicked
        lienzo.setColor(Color.yellow);
    }//GEN-LAST:event_boton_amarilloMouseClicked

    private void boton_verdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_verdeMouseClicked
        lienzo.setColor(Color.green);
    }//GEN-LAST:event_boton_verdeMouseClicked

    private void menu_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_abrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if(resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_menu_abrirActionPerformed

    private void menu_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if(resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_menu_guardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Edición;
    private javax.swing.JButton boton_amarillo;
    private javax.swing.JButton boton_azul;
    private javax.swing.JButton boton_blanco;
    private javax.swing.JToggleButton boton_elipse;
    private javax.swing.JToggleButton boton_lapiz;
    private javax.swing.JToggleButton boton_linea;
    private javax.swing.JButton boton_negro;
    private javax.swing.JToggleButton boton_rectangulo;
    private javax.swing.JButton boton_rojo;
    private javax.swing.JButton boton_verde;
    private javax.swing.ButtonGroup botones_colores;
    private javax.swing.ButtonGroup botones_herramientas;
    private javax.swing.JCheckBox check_relleno;
    private javax.swing.JLabel etiqueta_herramienta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private aplicacionpractica4.Lienzo lienzo;
    private javax.swing.JMenuItem menu_abrir;
    private javax.swing.JMenuItem menu_barra_estado;
    private javax.swing.JMenuItem menu_guardar;
    private javax.swing.JMenuItem menu_nuevo;
    // End of variables declaration//GEN-END:variables
}
