/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionpractica4;

import java.awt.Color;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JToggleButton;

/**
 *
 * @author nazaret
 */
public class VentantaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentantaPrincipal
     */
    public VentantaPrincipal() {
        initComponents();
        
        this.setTitle("Paint básico");
        this.setSize(600, 600);
        estado_barra = true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones_herramientas = new javax.swing.ButtonGroup();
        botones_colores = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        boton_lapiz = new javax.swing.JToggleButton();
        boton_linea = new javax.swing.JToggleButton();
        boton_rectangulo = new javax.swing.JToggleButton();
        boton_elipse = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        boton_negro = new javax.swing.JButton();
        boton_rojo = new javax.swing.JButton();
        boton_azul = new javax.swing.JButton();
        boton_blanco = new javax.swing.JButton();
        boton_amarillo = new javax.swing.JButton();
        boton_verde = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        check_relleno = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        etiqueta_herramienta = new javax.swing.JLabel();
        lienzo = new aplicacionpractica4.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        menu_nuevo = new javax.swing.JMenuItem();
        menu_abrir = new javax.swing.JMenuItem();
        menu_guardar = new javax.swing.JMenuItem();
        Edición = new javax.swing.JMenu();
        menu_barra_estado = new javax.swing.JCheckBoxMenuItem();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        botones_herramientas.add(boton_lapiz);
        boton_lapiz.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Lapiz.gif")); // NOI18N
        boton_lapiz.setFocusable(false);
        boton_lapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_lapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_lapiz.addMouseListener(formListener);
        jToolBar1.add(boton_lapiz);

        botones_herramientas.add(boton_linea);
        boton_linea.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Linea.gif")); // NOI18N
        boton_linea.setFocusable(false);
        boton_linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_linea.addMouseListener(formListener);
        jToolBar1.add(boton_linea);

        botones_herramientas.add(boton_rectangulo);
        boton_rectangulo.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Rectangulo.gif")); // NOI18N
        boton_rectangulo.setFocusable(false);
        boton_rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_rectangulo.addMouseListener(formListener);
        jToolBar1.add(boton_rectangulo);

        botones_herramientas.add(boton_elipse);
        boton_elipse.setIcon(new javax.swing.ImageIcon("/home/nazaret/Escritorio/ETSIIT_comp/3º/Cuatri 2/SMM/P2/Ovalo.gif")); // NOI18N
        boton_elipse.setFocusable(false);
        boton_elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_elipse.addMouseListener(formListener);
        jToolBar1.add(boton_elipse);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120)));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(2, 3));

        boton_negro.setBackground(new java.awt.Color(1, 1, 1));
        botones_colores.add(boton_negro);
        boton_negro.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_negro.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_negro.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_negro.addMouseListener(formListener);
        jPanel5.add(boton_negro);

        boton_rojo.setBackground(new java.awt.Color(255, 0, 0));
        botones_colores.add(boton_rojo);
        boton_rojo.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_rojo.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_rojo.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_rojo.addMouseListener(formListener);
        jPanel5.add(boton_rojo);

        boton_azul.setBackground(new java.awt.Color(0, 0, 255));
        botones_colores.add(boton_azul);
        boton_azul.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_azul.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_azul.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_azul.addMouseListener(formListener);
        jPanel5.add(boton_azul);

        boton_blanco.setBackground(new java.awt.Color(255, 255, 255));
        botones_colores.add(boton_blanco);
        boton_blanco.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_blanco.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_blanco.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_blanco.addMouseListener(formListener);
        jPanel5.add(boton_blanco);

        boton_amarillo.setBackground(new java.awt.Color(255, 255, 0));
        botones_colores.add(boton_amarillo);
        boton_amarillo.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_amarillo.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_amarillo.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_amarillo.addMouseListener(formListener);
        jPanel5.add(boton_amarillo);

        boton_verde.setBackground(new java.awt.Color(0, 255, 0));
        botones_colores.add(boton_verde);
        boton_verde.setMaximumSize(new java.awt.Dimension(30, 30));
        boton_verde.setMinimumSize(new java.awt.Dimension(20, 20));
        boton_verde.setPreferredSize(new java.awt.Dimension(25, 20));
        boton_verde.addMouseListener(formListener);
        jPanel5.add(boton_verde);

        jPanel6.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jPanel4, java.awt.BorderLayout.EAST);

        check_relleno.setText("Relleno ");
        check_relleno.addMouseListener(formListener);
        jPanel6.add(check_relleno, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120)));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        etiqueta_herramienta.setText("Punto");
        jPanel2.add(etiqueta_herramienta);

        jPanel3.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        jPanel1.add(lienzo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        Archivo.setText("Archivo");

        menu_nuevo.setText("Nuevo");
        menu_nuevo.addActionListener(formListener);
        Archivo.add(menu_nuevo);

        menu_abrir.setText("Abrir");
        menu_abrir.addActionListener(formListener);
        Archivo.add(menu_abrir);

        menu_guardar.setText("Guardar");
        menu_guardar.addActionListener(formListener);
        Archivo.add(menu_guardar);

        jMenuBar1.add(Archivo);

        Edición.setText("Edición");

        menu_barra_estado.setSelected(true);
        menu_barra_estado.setText("Ver barra de estado");
        menu_barra_estado.addActionListener(formListener);
        Edición.add(menu_barra_estado);

        jMenuBar1.add(Edición);

        setJMenuBar(jMenuBar1);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == menu_abrir) {
                VentantaPrincipal.this.menu_abrirActionPerformed(evt);
            }
            else if (evt.getSource() == menu_guardar) {
                VentantaPrincipal.this.menu_guardarActionPerformed(evt);
            }
            else if (evt.getSource() == menu_barra_estado) {
                VentantaPrincipal.this.menu_barra_estadoActionPerformed(evt);
            }
            else if (evt.getSource() == menu_nuevo) {
                VentantaPrincipal.this.menu_nuevoActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == boton_lapiz) {
                VentantaPrincipal.this.boton_lapizMouseClicked(evt);
            }
            else if (evt.getSource() == boton_linea) {
                VentantaPrincipal.this.boton_lineaMouseClicked(evt);
            }
            else if (evt.getSource() == boton_rectangulo) {
                VentantaPrincipal.this.boton_rectanguloMouseClicked(evt);
            }
            else if (evt.getSource() == boton_elipse) {
                VentantaPrincipal.this.boton_elipseMouseClicked(evt);
            }
            else if (evt.getSource() == boton_negro) {
                VentantaPrincipal.this.boton_negroMouseClicked(evt);
            }
            else if (evt.getSource() == boton_rojo) {
                VentantaPrincipal.this.boton_rojoMouseClicked(evt);
            }
            else if (evt.getSource() == boton_azul) {
                VentantaPrincipal.this.boton_azulMouseClicked(evt);
            }
            else if (evt.getSource() == boton_blanco) {
                VentantaPrincipal.this.boton_blancoMouseClicked(evt);
            }
            else if (evt.getSource() == boton_amarillo) {
                VentantaPrincipal.this.boton_amarilloMouseClicked(evt);
            }
            else if (evt.getSource() == boton_verde) {
                VentantaPrincipal.this.boton_verdeMouseClicked(evt);
            }
            else if (evt.getSource() == check_relleno) {
                VentantaPrincipal.this.check_rellenoMouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void boton_lapizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_lapizMouseClicked
        lienzo.setHerramienta(TipoHerramienta.PUNTOS);
        etiqueta_herramienta.setText("Punto");
    }//GEN-LAST:event_boton_lapizMouseClicked

    private void boton_lineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_lineaMouseClicked
        lienzo.setHerramienta(TipoHerramienta.LINEAS);
        etiqueta_herramienta.setText("Línea");
    }//GEN-LAST:event_boton_lineaMouseClicked

    private void boton_rectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_rectanguloMouseClicked
        lienzo.setHerramienta(TipoHerramienta.RECTANGULOS);
        etiqueta_herramienta.setText("Rectángulo");
    }//GEN-LAST:event_boton_rectanguloMouseClicked

    private void boton_elipseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_elipseMouseClicked
        lienzo.setHerramienta(TipoHerramienta.ELIPSES);
        etiqueta_herramienta.setText("Elipse");
    }//GEN-LAST:event_boton_elipseMouseClicked

    private void check_rellenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_rellenoMouseClicked
        if(check_relleno.isSelected())
            lienzo.setRelleno(true);
        else
            lienzo.setRelleno(false);
    }//GEN-LAST:event_check_rellenoMouseClicked

    private void boton_negroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_negroMouseClicked
        lienzo.setColor(Color.black);
    }//GEN-LAST:event_boton_negroMouseClicked

    private void boton_rojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_rojoMouseClicked
        lienzo.setColor(Color.red);
    }//GEN-LAST:event_boton_rojoMouseClicked

    private void boton_azulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_azulMouseClicked
        lienzo.setColor(Color.blue);
    }//GEN-LAST:event_boton_azulMouseClicked

    private void boton_blancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_blancoMouseClicked
        lienzo.setColor(Color.white);
    }//GEN-LAST:event_boton_blancoMouseClicked

    private void boton_amarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_amarilloMouseClicked
        lienzo.setColor(Color.yellow);
    }//GEN-LAST:event_boton_amarilloMouseClicked

    private void boton_verdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_verdeMouseClicked
        lienzo.setColor(Color.green);
    }//GEN-LAST:event_boton_verdeMouseClicked

    private void menu_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_abrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if(resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_menu_abrirActionPerformed

    private void menu_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if(resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_menu_guardarActionPerformed

    private void menu_barra_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_barra_estadoActionPerformed
        estado_barra = !estado_barra;
        jPanel2.setVisible(estado_barra);
    }//GEN-LAST:event_menu_barra_estadoActionPerformed

    private void menu_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_nuevoActionPerformed
        lienzo.borrar();
    }//GEN-LAST:event_menu_nuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenu Edición;
    private javax.swing.JButton boton_amarillo;
    private javax.swing.JButton boton_azul;
    private javax.swing.JButton boton_blanco;
    private javax.swing.JToggleButton boton_elipse;
    private javax.swing.JToggleButton boton_lapiz;
    private javax.swing.JToggleButton boton_linea;
    private javax.swing.JButton boton_negro;
    private javax.swing.JToggleButton boton_rectangulo;
    private javax.swing.JButton boton_rojo;
    private javax.swing.JButton boton_verde;
    private javax.swing.ButtonGroup botones_colores;
    private javax.swing.ButtonGroup botones_herramientas;
    private javax.swing.JCheckBox check_relleno;
    private javax.swing.JLabel etiqueta_herramienta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar jToolBar1;
    private aplicacionpractica4.Lienzo lienzo;
    private javax.swing.JMenuItem menu_abrir;
    private javax.swing.JCheckBoxMenuItem menu_barra_estado;
    private javax.swing.JMenuItem menu_guardar;
    private javax.swing.JMenuItem menu_nuevo;
    // End of variables declaration//GEN-END:variables
    private boolean estado_barra;
}
