/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.nrg.iu;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author nazaret
 */
public class LienzoImagen2D extends Lienzo2D {

    /**
     * Creates new form LienzoImagen2D
     */
    public LienzoImagen2D() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        if(img != null)
            g.drawImage(img, 0, 0, this);
        
    }
    
    public void setImagen(BufferedImage img){
        this.img = img;
        
        if(img != null)
            setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
    }
    
    public BufferedImage getImagen(boolean draw_vector){
        if(draw_vector){
            BufferedImage aux = new BufferedImage(img.getWidth(), img.getHeight(), img.getType());
            
            Graphics2D g2d = aux.createGraphics();
            g2d.drawImage(img, img.getWidth(), img.getHeight(), this);
            
            // REVISAR EN P10 (FALLA CON TRANSPARENCIA)
            super.paint(g2d);
            
            return aux;
        }
        
        return img;
    }
    
    private BufferedImage img;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
